import {
    Users, Building2, Shield, Key,
    CheckCircle, Eye, Edit, Trash2, FilePlus, ThumbsUp,
    DollarSign, FolderOpen, ClipboardList, FileText, Package, Landmark,
    Receipt, Settings, Bot, BarChart3, FileCheck, Briefcase, Scale,
    ShoppingCart, Truck, Award, Warehouse,
    UserCheck, Lock, Star, Zap,
    Terminal, Navigation, Search,
    RefreshCw, LayoutDashboard,
} from 'lucide-react';

export const SYSTEM_MODULES = [
    {
        icon: FolderOpen, color: 'bg-indigo-500', label: 'Projects',
        desc: 'Create and manage projects end-to-end, including budgets, deliverables, tenders, and progress tracking across multiple phases.',
        features: [
            'Create projects with detailed budget allocations',
            'Track milestones, progress percentage, and deadlines',
            'Manage tender submissions and evaluations',
            'Link projects to contracts, task orders, and invoices',
            'Budget vs. actual spend comparison',
            'Multi-stage approval workflow for project creation',
        ],
        route: '/projects',
        howTo: [
            { title: 'Creating a Project', steps: ['Navigate to Projects from the dashboard', 'Click "Create Project" button or use the sidebar link', 'Fill in the project name, description, start date, and deadline', 'Set the budget allocation and currency', 'Add any related documents or attachments', 'Click "Submit" to create the project in Draft status', 'The project will require approval before becoming active'] },
            { title: 'Tracking Progress', steps: ['Open the project from the Projects list', 'View the progress bar and milestone timeline', 'Update the completion percentage as work progresses', 'Add status notes for each milestone update', 'The system logs all progress changes automatically'] },
            { title: 'Managing Tenders', steps: ['Navigate to the project details page', 'Click "Tenders" tab to view associated tenders', 'Click "Create Tender" to add a new tender submission', 'Fill in tender requirements, pricing, and deadline', 'Submit the tender for review'] },
        ],
    },
    {
        icon: Users, color: 'bg-purple-500', label: 'Clients',
        desc: 'Manage client profiles, contacts, contracts, and multi-stage approval workflows. Track client relationships from initial contact to contract execution.',
        features: [
            'Add clients with full contact details and documents',
            'Create and manage client contracts with terms',
            'Submit client records for multi-stage approval',
            'Track approval status (Pending, Approved, Rejected)',
            'View complete client timeline and history',
            'Link clients to projects and invoices',
        ],
        route: '/clients',
        howTo: [
            { title: 'Adding a New Client', steps: ['Navigate to Clients from the dashboard', 'Click "Create Client" button', 'Enter the client company name and registration details', 'Add primary contact person, phone, and email', 'Upload any supporting documents (trade license, etc.)', 'Submit the client for approval'] },
            { title: 'Creating a Client Contract', steps: ['Navigate to Client Contracts from the sidebar', 'Click "Create Client Contract"', 'Select the client from the dropdown', 'Enter contract terms, value, start and end dates', 'Add contract clauses and special conditions', 'Submit for the approval workflow'] },
            { title: 'Tracking Approvals', steps: ['Go to Pending Requests in the sidebar', 'View all clients awaiting approval', 'Click on a client to see full details', 'Approved clients appear in the Approved list', 'Each approval step is timestamped in the timeline'] },
        ],
    },
    {
        icon: FileCheck, color: 'bg-teal-500', label: 'Project Contracts',
        desc: 'Manage contractor agreements, execution tracking, change order management, and contractor payments with full audit trails.',
        features: [
            'Issue contracts to subcontractors with detailed terms',
            'Track contract milestones and deliverables',
            'Process contract amendments and change orders',
            'Manage contractor profiles and contact information',
            'Multi-stage approval for contract creation',
            'Link contracts to projects and financial records',
        ],
        route: '/contracts/contracts',
        howTo: [
            { title: 'Creating a Contract', steps: ['Navigate to Project Contracts from the dashboard', 'Click "Create Contract" in the sidebar', 'Select the associated project and contractor', 'Enter contract value, terms, and milestone schedule', 'Attach relevant documents (BOQ, specifications)', 'Submit for multi-stage approval'] },
            { title: 'Managing Contractors', steps: ['Navigate to Contractors in the sidebar', 'Click "Create Contractor" to add a new subcontractor', 'Enter company details, license, and contact information', 'View all contracts associated with each contractor'] },
        ],
    },
    {
        icon: ClipboardList, color: 'bg-amber-500', label: 'Task Orders',
        desc: 'Work orders, change orders, and field task assignments with approval workflows. Track task execution from creation to completion.',
        features: [
            'Create task orders linked to projects and contracts',
            'Submit and manage change order requests',
            'Approve or reject field task completions',
            'Track task progress and completion status',
            'Multi-stage approval for task orders',
            'Detailed task history and timeline view',
        ],
        route: '/tasks',
        howTo: [
            { title: 'Creating a Task Order', steps: ['Navigate to Task Orders from the dashboard', 'Click "Create Task" from the sidebar', 'Select the associated project and contract', 'Describe the scope of work and deliverables', 'Set the deadline and assign to a team', 'Submit for approval through the workflow'] },
            { title: 'Submitting a Change Order', steps: ['Navigate to Change Orders in the sidebar', 'Click "Create Change Order"', 'Select the original task order to modify', 'Describe the changes and cost implications', 'Submit for review and approval'] },
        ],
    },
    {
        icon: DollarSign, color: 'bg-emerald-500', label: 'Financial',
        desc: 'Complete financial management including disbursements, loans, cash ledger, petty cash, payroll, contractor payments, budgets, and financial reporting.',
        features: [
            'Create and process payment disbursements',
            'Financial request inbox with approval workflow',
            'Petty cash management and tracking',
            'Cash ledger and financial ledger views',
            'Contractor payment processing and tracking',
            'Project budget management and forecasting',
            'Loan management and repayment tracking',
            'Financial reporting and export capabilities',
        ],
        route: '/financial',
        howTo: [
            { title: 'Creating a Disbursement', steps: ['Navigate to Financial > Disbursements', 'Click "New Disbursement"', 'Enter the payment amount, recipient, and purpose', 'Select the payment method and bank account', 'Attach supporting invoices or documents', 'Submit for the multi-stage approval chain (Staff → Manager → CFO → CEO)'] },
            { title: 'Managing Petty Cash', steps: ['Navigate to Financial > Petty Cash', 'View current petty cash balance and transactions', 'Record new expenses with receipts', 'Track who withdrew funds and for what purpose'] },
            { title: 'Managing Loans', steps: ['Navigate to Financial > Loans', 'View all active loans and repayment schedules', 'Create new loan records with terms', 'Track repayment progress and remaining balances'] },
        ],
    },
    {
        icon: Users, color: 'bg-blue-500', label: 'Users & HR',
        desc: 'Employee records, user accounts, roles, permissions, departments, and organizational structure management with fine-grained access control.',
        features: [
            'Create and manage employee records with job titles',
            'User account creation with role assignment',
            'Assign roles and control access for each user',
            'Adjust individual permissions as needed',
            'Department management and org structure',
            'Employee document management',
        ],
        route: '/users',
        howTo: [
            { title: 'Creating a User Account', steps: ['Navigate to Users from the dashboard', 'Click "Create User"', 'Enter name, surname, email (username@beam.local), and phone', 'Assign a role from the dropdown (determines default permissions)', 'Set the initial password', 'The user can now log in with their credentials'] },
            { title: 'Managing Employee Records', steps: ['Navigate to Employees in the sidebar', 'Click "Create Employee" to add a new record', 'Enter personal info, job title, department, and salary', 'Link the employee to an existing user account', 'Upload employee documents (ID, contract, etc.)'] },
            { title: 'Configuring Permissions', steps: ['Navigate to Permissions in the sidebar', 'View the full permission matrix by role', 'To adjust a specific user\'s permissions, go to Users > User Permissions', 'Toggle individual flags (View, Create, Edit, Delete, Approve)', 'Changes take effect within a few minutes'] },
        ],
    },
    {
        icon: Package, color: 'bg-orange-500', label: 'Inventory',
        desc: 'Stock management, item tracking, movements, and warehouse records. Track inventory quantities, movements, and generate stock reports.',
        features: [
            'Add and manage inventory items with quantities',
            'Record stock movements (in/out) with details',
            'Track item locations and warehouse assignments',
            'View transaction history for each item',
            'Generate stock level reports',
            'Low stock alerts and notifications',
        ],
        route: '/inventory/items',
        howTo: [
            { title: 'Adding Inventory Items', steps: ['Navigate to Inventory > Items', 'Click to add a new item', 'Enter item name, SKU, category, and unit', 'Set initial quantity and minimum stock level', 'Assign to a warehouse location'] },
            { title: 'Recording Stock Movements', steps: ['Navigate to Inventory > Transactions', 'Record an "In" transaction for received goods', 'Record an "Out" transaction for issued goods', 'Each transaction updates the running balance', 'View complete movement history per item'] },
        ],
    },
    {
        icon: Landmark, color: 'bg-cyan-500', label: 'Banks',
        desc: 'Bank accounts, balances, exchange offices, and fund tracking. Manage multiple bank accounts and monitor fund movements.',
        features: [
            'Add and manage bank accounts with details',
            'Track account balances over time',
            'Exchange office (Sarrafat) management',
            'Exchange balance tracking and reconciliation',
            'Bank balance recording and reporting',
            'Multi-currency support',
        ],
        route: '/banks',
        howTo: [
            { title: 'Adding a Bank Account', steps: ['Navigate to Banks from the dashboard', 'Click "Create Bank"', 'Enter bank name, branch, account number, and IBAN', 'Set the currency and initial balance', 'The account is now ready for transactions'] },
            { title: 'Managing Exchange Offices', steps: ['Navigate to Exchange List in the sidebar', 'Click "Create Exchange" to add a new exchange office', 'Enter the office name, location, and contact details', 'Track exchange rates and balances separately'] },
        ],
    },
    {
        icon: Receipt, color: 'bg-rose-500', label: 'Invoices',
        desc: 'Invoice creation, payment tracking, and invoice reporting. Generate professional invoices linked to clients and projects.',
        features: [
            'Create client invoices with line items',
            'Mark invoices as paid, partially paid, or overdue',
            'Export invoice reports as PDF or CSV',
            'Link invoices to projects and contracts',
            'Track payment status and history',
            'Invoice numbering and sequencing',
        ],
        route: '/invoices',
        howTo: [
            { title: 'Creating an Invoice', steps: ['Navigate to Invoices from the dashboard', 'Click "Add Invoice"', 'Select the client and project', 'Add line items with descriptions, quantities, and amounts', 'Set the due date and payment terms', 'Save and optionally export as PDF'] },
        ],
    },
    {
        icon: FileText, color: 'bg-brand-sky-500', label: 'Documents',
        desc: 'Official documents, file attachments, and document archiving. Centralized document management for the entire organization.',
        features: [
            'Upload and categorize official documents',
            'Attach supporting files to projects and records',
            'Document archiving and retrieval',
            'Version tracking and file management',
            'Search across all documents',
            'Access control per document type',
        ],
        route: '/documents',
        howTo: [
            { title: 'Uploading Documents', steps: ['Navigate to Documents from the dashboard', 'Click "Add Document"', 'Select the document category and type', 'Upload the file (PDF, Word, Excel, images)', 'Add a description and tags for search', 'Link to a project or record if applicable'] },
        ],
    },
    {
        icon: BarChart3, color: 'bg-violet-500', label: 'Reports & Analysis',
        desc: 'Reports, statistics, dashboards, and business data analytics. Generate comprehensive reports across all system modules.',
        features: [
            'Generate monthly and annual financial reports',
            'Project KPI analysis and benchmarking',
            'Budget vs. actual spend comparisons',
            'Statistical dashboards with visual charts',
            'Export reports in multiple formats',
            'Custom date range filtering',
        ],
        route: '/reports',
        howTo: [
            { title: 'Generating Reports', steps: ['Navigate to Reports from the dashboard', 'Select the report type (Financial, Project, HR, etc.)', 'Set the date range and any filters', 'Click "Generate Report"', 'View the report with charts and tables', 'Export as PDF or CSV'] },
        ],
    },
    {
        icon: Bot, color: 'bg-fuchsia-500', label: 'AI Assistant',
        desc: 'Intelligent chat, financial analysis, forecasting, anomaly detection, smart summarization, and AI-powered insights across all modules.',
        features: [
            'AI Chat — Ask questions about any system data',
            'Financial Analysis — AI-driven financial insights',
            'Project Analysis — Analyze project performance',
            'Employee Performance — HR analytics with AI',
            'Anomaly Detection — Detect unusual transactions',
            'Budget Forecasting — Predict future spending',
            'Smart Summarization — Summarize large datasets',
            'Tender Evaluation — AI-assisted tender scoring',
            'Approval Advisor — Smart approval recommendations',
            'Data Query — Natural language data queries',
            'Dashboard Insights — AI-generated dashboard summaries',
        ],
        route: '/ai',
        howTo: [
            { title: 'Using AI Chat', steps: ['Navigate to AI Assistant from the dashboard', 'Select "AI Chat" from the module grid', 'Type your question in natural language', 'The AI analyzes your data and responds', 'Ask follow-up questions for deeper insights'] },
            { title: 'Financial Analysis', steps: ['Navigate to AI > Financial Analysis', 'The AI automatically scans financial data', 'View insights on spending trends and anomalies', 'Get budget recommendations and forecasts'] },
        ],
    },
    {
        icon: CheckCircle, color: 'bg-pink-500', label: 'Approvals',
        desc: 'Multi-stage approval workflows for requests, contracts, and payments. Review, approve, or reject with comments and full audit trails.',
        features: [
            'View all pending approvals in a single dashboard',
            'Approve or reject requests with comments',
            'Multi-stage approval chains (Staff → Manager → Director → CEO)',
            'Approval timeline and history tracking',
            'Email notifications for pending approvals',
            'Delegation and escalation support',
        ],
        route: '/approvals',
        howTo: [
            { title: 'Reviewing Approvals', steps: ['Navigate to Approvals from the dashboard or Requests module', 'View all items pending your approval', 'Click an item to see full details and history', 'Add a comment explaining your decision', 'Click "Approve" or "Reject"', 'The system notifies the next person in the chain'] },
        ],
    },
    {
        icon: Settings, color: 'bg-slate-500', label: 'Settings',
        desc: 'User profile management, notification preferences, system history, and application configuration.',
        features: [
            'Update personal profile and avatar',
            'Change password securely',
            'Configure email notification preferences',
            'View system-wide activity history',
            'Manage user session settings',
            'Application appearance preferences',
        ],
        route: '/settings',
        howTo: [
            { title: 'Updating Your Profile', steps: ['Navigate to Settings from the dashboard', 'Click "Profile" in the sidebar', 'Update your name, phone, or avatar', 'Click "Save Changes"'] },
            { title: 'Changing Your Password', steps: ['Navigate to Settings > Profile', 'Scroll to the password section', 'Enter your current password', 'Enter and confirm your new password', 'Click "Update Password"'] },
        ],
    },
];

export const DEPARTMENTS = [
    {
        id: 'EXEC', icon: Star, color: 'from-amber-500 to-orange-500',
        bg: 'bg-amber-50 dark:bg-amber-950/20', border: 'border-amber-200 dark:border-amber-800',
        name: 'Executive Office',
        desc: 'Strategic leadership, executive decision-making, and cross-department coordination. The executive office oversees all company operations and provides final approval on high-value transactions.',
        longDesc: 'The Executive Office is the highest authority within the organization. Led by the CEO, this department is responsible for setting strategic direction, making critical business decisions, and ensuring alignment across all departments. Members have view access to the entire system and serve as the final approvers in multi-stage workflows for high-value transactions, contracts, and disbursements.',
        roles: ['CEO'], heads: ['Chief Executive Officer', 'Deputy CEO'],
        access: ['Full system (view)', 'Executive decisions', 'Final approvals', 'Cross-department oversight'],
        responsibilities: ['Set company strategy and vision', 'Final approval on high-value contracts and payments', 'Cross-department coordination and conflict resolution', 'Stakeholder communication and reporting'],
    },
    {
        id: 'FINANCE', icon: DollarSign, color: 'from-emerald-500 to-green-600',
        bg: 'bg-emerald-50 dark:bg-emerald-950/20', border: 'border-emerald-200 dark:border-emerald-800',
        name: 'Financial Department',
        desc: 'Budget management, accounts, disbursements, payroll, and financial reporting. Responsible for all monetary transactions and financial compliance.',
        longDesc: 'The Financial Department manages all monetary aspects of the organization. From processing disbursements and managing petty cash to tracking loans and generating financial reports, this team ensures fiscal responsibility and compliance. The department operates with a clear hierarchy: FIN_STAFF creates transactions, FIN_MGR reviews and validates, and the CFO provides final financial authorization.',
        roles: ['CFO', 'FIN_MGR', 'FIN_STAFF'], heads: ['CFO', 'Finance Director', 'Financial Controller'],
        access: ['Financial module (full)', 'Budgets', 'Disbursements', 'Approvals', 'Contracts (view)', 'Loans'],
        responsibilities: ['Process all payment disbursements', 'Manage budgets and financial planning', 'Track loans, petty cash, and ledger entries', 'Generate financial reports and statements', 'Ensure compliance with financial policies'],
    },
    {
        id: 'HR', icon: UserCheck, color: 'from-blue-500 to-indigo-600',
        bg: 'bg-blue-50 dark:bg-blue-950/20', border: 'border-blue-200 dark:border-blue-800',
        name: 'Human Resources',
        desc: 'Employee management, hiring, payroll, performance evaluations, and HR administration. Manages the complete employee lifecycle from onboarding to offboarding.',
        longDesc: 'Human Resources manages the people side of the organization. This department handles employee records, hiring, payroll coordination, performance reviews, and compliance with labor regulations. HR staff can create and manage employee records, while the HR Director has broader access including payroll oversight and financial viewing capabilities.',
        roles: ['HR_DIR', 'HR_STAFF'], heads: ['HR Director', 'HR Manager'],
        access: ['Employees (full)', 'Payroll', 'Employee documents', 'Financial (view)'],
        responsibilities: ['Manage employee records and onboarding', 'Coordinate payroll with Finance', 'Handle performance evaluations', 'Maintain HR compliance and documentation', 'Process employee requests and updates'],
    },
    {
        id: 'IT', icon: Terminal, color: 'from-violet-500 to-purple-600',
        bg: 'bg-violet-50 dark:bg-violet-950/20', border: 'border-violet-200 dark:border-violet-800',
        name: 'Information Technology',
        desc: 'System administration, user accounts, roles, permissions, and IT infrastructure. Manages all technical aspects of BEAM and provides user support.',
        longDesc: 'The IT Department manages user accounts, configures roles and permissions, handles system settings, and provides support to all users. IT staff have the unique ability to adjust individual user permissions, allowing them to give or remove specific access for a person without changing their overall role.',
        roles: ['IT_DIR', 'IT_STAFF'], heads: ['IT Director', 'Systems Manager'],
        access: ['Users (full)', 'Roles', 'Permissions', 'Audit logs', 'System configuration'],
        responsibilities: ['Create and manage user accounts', 'Configure roles and permission matrices', 'Apply user-level permission overrides', 'Monitor system health and audit logs', 'Provide technical support to all departments'],
    },
    {
        id: 'LEGAL', icon: Scale, color: 'from-slate-500 to-gray-600',
        bg: 'bg-slate-50 dark:bg-slate-950/20', border: 'border-slate-200 dark:border-slate-700',
        name: 'Legal Department',
        desc: 'Legal affairs, contract review, regulatory compliance, and legal representation. Reviews all contracts and ensures legal compliance across operations.',
        longDesc: 'The Legal Department ensures all organizational operations comply with applicable laws and regulations. They review all contracts before execution, provide legal opinions on business decisions, and manage legal documentation. The Legal Director participates in the contract approval workflow, providing a mandatory legal review step before final execution.',
        roles: ['LEG_DIR', 'LEG_STAFF'], heads: ['Legal Director', 'Legal Advisor'],
        access: ['Legal documents (full)', 'Contracts (view)', 'Compliance'],
        responsibilities: ['Review all contracts for legal compliance', 'Provide legal opinions on business matters', 'Manage legal documentation and records', 'Participate in contract approval workflows', 'Ensure regulatory compliance'],
    },
    {
        id: 'PROC', icon: ShoppingCart, color: 'from-orange-500 to-red-500',
        bg: 'bg-orange-50 dark:bg-orange-950/20', border: 'border-orange-200 dark:border-orange-800',
        name: 'Procurement & Supply Chain',
        desc: 'Purchasing operations, supplier management, and supply chain logistics. Manages procurement processes from requisition to delivery.',
        longDesc: 'The Procurement & Supply Chain department handles all purchasing activities, supplier relationships, and logistics. They manage the complete procurement lifecycle from requisition to delivery, ensuring the organization gets the best value while maintaining quality standards.',
        roles: ['PROC_DIR', 'PROC_STAFF'], heads: ['Supply Chain Director', 'Procurement Manager'],
        access: ['Procurement (full)', 'Warehouse (view)', 'Financial (view)', 'Suppliers'],
        responsibilities: ['Process purchase requisitions and orders', 'Manage supplier relationships', 'Negotiate pricing and terms', 'Coordinate with Warehouse for deliveries', 'Track procurement spending'],
    },
    {
        id: 'OPS', icon: Briefcase, color: 'from-yellow-500 to-amber-600',
        bg: 'bg-yellow-50 dark:bg-yellow-950/20', border: 'border-yellow-200 dark:border-yellow-800',
        name: 'Operations & Deployment',
        desc: 'Project execution, contractor management, and field work order supervision. Oversees day-to-day operational activities and project delivery.',
        longDesc: 'The Operations & Deployment department is responsible for executing projects on the ground. They create and manage task orders, supervise field work, coordinate with contractors, and ensure deliverables meet specifications and timelines. Operations staff work closely with Quality Management for inspection sign-offs.',
        roles: ['OPS_MGR', 'OPS_STAFF'], heads: ['Program Director Operations', 'Project Manager'],
        access: ['Operations (full)', 'Task orders', 'Contracts (view)', 'Quality (view)'],
        responsibilities: ['Create and execute task orders', 'Supervise field operations', 'Coordinate with contractors', 'Report project progress', 'Manage operational resources'],
    },
    {
        id: 'QUALITY', icon: Award, color: 'from-teal-500 to-cyan-600',
        bg: 'bg-teal-50 dark:bg-teal-950/20', border: 'border-teal-200 dark:border-teal-800',
        name: 'Quality Management',
        desc: 'Quality assurance, internal auditing, standards compliance, and process improvement. Ensures all deliverables meet quality standards.',
        longDesc: 'Quality Management ensures all work products and deliverables meet established standards. The team conducts inspections, performs quality audits, and provides the final sign-off on completed task orders. They work across departments to maintain and improve quality processes.',
        roles: ['QA_DIR', 'QA_STAFF'], heads: ['Quality Director', 'QA Manager'],
        access: ['Quality inspections (full)', 'Operations (view)', 'Reports'],
        responsibilities: ['Conduct quality inspections', 'Sign off on completed task orders', 'Maintain quality standards documentation', 'Perform internal quality audits', 'Recommend process improvements'],
    },
    {
        id: 'FLEET', icon: Truck, color: 'from-brand-sky-500 to-blue-600',
        bg: 'bg-brand-sky-50 dark:bg-brand-sky-950/20', border: 'border-brand-sky-200 dark:border-brand-sky-800',
        name: 'Fleet Management',
        desc: 'Vehicle and equipment management, scheduled maintenance, and fleet operations. Tracks all company vehicles, equipment, and their maintenance schedules.',
        longDesc: 'Fleet Management oversees all company vehicles and heavy equipment. The department tracks vehicle assignments, schedules preventive maintenance, manages fuel consumption, and ensures all equipment is operational and compliant with safety regulations.',
        roles: ['FLEET_DIR', 'FLEET_STAFF'], heads: ['Fleet Director', 'Equipment Supervisor'],
        access: ['Fleet records (full)', 'Maintenance schedules', 'Equipment tracking'],
        responsibilities: ['Manage vehicle and equipment records', 'Schedule and track maintenance', 'Monitor fuel consumption', 'Ensure fleet safety compliance', 'Coordinate equipment assignments'],
    },
    {
        id: 'WAREHOUSE', icon: Warehouse, color: 'from-lime-500 to-green-600',
        bg: 'bg-lime-50 dark:bg-lime-950/20', border: 'border-lime-200 dark:border-lime-800',
        name: 'Warehouse & Stores',
        desc: 'Inventory management, goods receipt and dispatch, and warehouse movements. Manages physical storage locations and stock levels.',
        longDesc: 'Warehouse & Stores manages all physical inventory and storage operations. The team handles goods receipt, storage allocation, dispatch, and stock level monitoring. They work closely with Procurement to receive ordered materials and with Operations to dispatch required supplies to project sites.',
        roles: ['WH_DIR', 'WH_STAFF'], heads: ['Warehouse Director', 'Warehouse Manager'],
        access: ['Warehouse (full)', 'Inventory', 'Stock movements', 'Procurement (view)'],
        responsibilities: ['Manage goods receipt and dispatch', 'Maintain accurate stock levels', 'Organize warehouse storage', 'Record all stock movements', 'Coordinate with Procurement and Operations'],
    },
    {
        id: 'COMMERCIAL', icon: FileCheck, color: 'from-pink-500 to-rose-600',
        bg: 'bg-pink-50 dark:bg-pink-950/20', border: 'border-pink-200 dark:border-pink-800',
        name: 'Commercial & Contracts',
        desc: 'Commercial contract management, revenue assurance, and contract negotiations. Manages all commercial aspects including pricing and contract terms.',
        longDesc: 'The Commercial & Contracts department manages all contractual relationships. The Commercial Director leads contract negotiations, reviews pricing, and ensures commercial terms are favorable. Contracts Staff handle the day-to-day management of contract documentation, milestones, and change orders.',
        roles: ['COM_DIR', 'CON_STAFF'], heads: ['Commercial Director', 'Contracts Engineer'],
        access: ['Contracts (full)', 'Approvals', 'Financial (view)', 'Client contracts'],
        responsibilities: ['Draft and negotiate contracts', 'Manage contract milestones and amendments', 'Review commercial terms and pricing', 'Process change orders', 'Participate in contract approval workflows'],
    },
    {
        id: 'AUDIT', icon: Eye, color: 'from-red-500 to-rose-600',
        bg: 'bg-red-50 dark:bg-red-950/20', border: 'border-red-200 dark:border-red-800',
        name: 'Internal Audit',
        desc: 'Full internal audit across all operations, ensuring compliance and transparency. Has view access to all modules for comprehensive auditing.',
        longDesc: 'Internal Audit provides independent assurance that the organization\'s operations are conducted in compliance with policies and procedures. The Audit Director has broad view access across Financial, HR, Contracts, Operations, and Quality modules, enabling comprehensive cross-departmental auditing without the ability to modify records.',
        roles: ['AUDIT_DIR'], heads: ['Internal Audit Director'],
        access: ['Audit (full)', 'View: Financial, HR, Contracts, Operations, Quality', 'Audit reports'],
        responsibilities: ['Conduct internal audits across all departments', 'Review financial transactions for compliance', 'Assess operational efficiency', 'Report findings to executive management', 'Recommend controls and improvements'],
    },
    {
        id: 'ADMIN', icon: Shield, color: 'from-rose-500 to-pink-600',
        bg: 'bg-rose-50 dark:bg-rose-950/20', border: 'border-rose-200 dark:border-rose-800',
        name: 'System Administration',
        desc: 'Full system access — manages all users, roles, permissions, and system settings. This role has unrestricted access to every part of the system.',
        longDesc: 'System Administration has complete, unrestricted access to every module and resource in BEAM. This role can access everything without any restrictions. It is reserved for managing the system, performing emergency operations, and configuring core settings. This role should only be assigned to 1-2 trusted administrators.',
        roles: ['SYSADMIN'], heads: ['System Administrator'],
        access: ['Full system bypass', 'All modules', 'All permissions', 'System configuration'],
        responsibilities: ['Full system administration', 'Emergency access and recovery', 'System configuration and maintenance', 'User and role management (unrestricted)', 'Data integrity and backup oversight'],
    },
];

export const ROLES_MATRIX = [
    { role: 'SYSADMIN', label: 'System Administrator', bypass: true, perms: 59, type: 'Admin', username: 'admin', password: 'Admin@2026!' },
    { role: 'CEO', label: 'Chief Executive Officer', bypass: false, perms: 14, type: 'Executive', username: 'ceo', password: 'Beam@2026' },
    { role: 'AUDIT_DIR', label: 'Internal Audit Director', bypass: false, perms: 7, type: 'Audit', username: 'audit_dir', password: 'Beam@2026' },
    { role: 'CFO', label: 'Chief Financial Officer', bypass: false, perms: 14, type: 'Finance', username: 'cfo', password: 'Beam@2026' },
    { role: 'FIN_MGR', label: 'Finance Manager', bypass: false, perms: 12, type: 'Finance', username: 'fin_mgr', password: 'Beam@2026' },
    { role: 'FIN_STAFF', label: 'Finance Staff', bypass: false, perms: 7, type: 'Finance', username: 'fin_staff', password: 'Beam@2026' },
    { role: 'HR_DIR', label: 'HR Director', bypass: false, perms: 8, type: 'HR', username: 'hr_dir', password: 'Beam@2026' },
    { role: 'HR_STAFF', label: 'HR Staff', bypass: false, perms: 5, type: 'HR', username: 'hr_staff', password: 'Beam@2026' },
    { role: 'IT_DIR', label: 'IT Director', bypass: false, perms: 8, type: 'IT', username: 'it_dir', password: 'Beam@2026' },
    { role: 'IT_STAFF', label: 'IT Staff', bypass: false, perms: 6, type: 'IT', username: 'it_staff', password: 'Beam@2026' },
    { role: 'LEG_DIR', label: 'Legal Director', bypass: false, perms: 5, type: 'Legal', username: 'leg_dir', password: 'Beam@2026' },
    { role: 'LEG_STAFF', label: 'Legal Staff', bypass: false, perms: 4, type: 'Legal', username: 'leg_staff', password: 'Beam@2026' },
    { role: 'PROC_DIR', label: 'Procurement Director', bypass: false, perms: 7, type: 'Procurement', username: 'proc_dir', password: 'Beam@2026' },
    { role: 'PROC_STAFF', label: 'Procurement Staff', bypass: false, perms: 4, type: 'Procurement', username: 'proc_staff', password: 'Beam@2026' },
    { role: 'OPS_MGR', label: 'Operations Manager', bypass: false, perms: 7, type: 'Operations', username: 'ops_mgr', password: 'Beam@2026' },
    { role: 'OPS_STAFF', label: 'Operations Staff', bypass: false, perms: 5, type: 'Operations', username: 'ops_staff', password: 'Beam@2026' },
    { role: 'QA_DIR', label: 'Quality Director', bypass: false, perms: 5, type: 'Quality', username: 'qa_dir', password: 'Beam@2026' },
    { role: 'QA_STAFF', label: 'Quality Staff', bypass: false, perms: 4, type: 'Quality', username: 'qa_staff', password: 'Beam@2026' },
    { role: 'FLEET_DIR', label: 'Fleet Director', bypass: false, perms: 3, type: 'Fleet', username: 'fleet_dir', password: 'Beam@2026' },
    { role: 'FLEET_STAFF', label: 'Fleet Staff', bypass: false, perms: 3, type: 'Fleet', username: 'fleet_staff', password: 'Beam@2026' },
    { role: 'WH_DIR', label: 'Warehouse Director', bypass: false, perms: 4, type: 'Warehouse', username: 'wh_dir', password: 'Beam@2026' },
    { role: 'WH_STAFF', label: 'Warehouse Staff', bypass: false, perms: 3, type: 'Warehouse', username: 'wh_staff', password: 'Beam@2026' },
    { role: 'COM_DIR', label: 'Commercial Director', bypass: false, perms: 9, type: 'Contracts', username: 'com_dir', password: 'Beam@2026' },
    { role: 'CON_STAFF', label: 'Contracts Staff', bypass: false, perms: 4, type: 'Contracts', username: 'con_staff', password: 'Beam@2026' },
];

export const PERMISSION_FLAGS = [
    { key: 'view', icon: Eye, label: 'View', color: 'text-blue-500', desc: 'See records, open pages, and browse data within the module.' },
    { key: 'create', icon: FilePlus, label: 'Create', color: 'text-green-500', desc: 'Add new records — for example, create a project or add an employee.' },
    { key: 'edit', icon: Edit, label: 'Edit', color: 'text-amber-500', desc: 'Update existing records — for example, modify a contract or edit a salary.' },
    { key: 'delete', icon: Trash2, label: 'Delete', color: 'text-red-500', desc: 'Remove records from the system.' },
    { key: 'approve', icon: ThumbsUp, label: 'Approve', color: 'text-purple-500', desc: 'Sign off on pending requests, payments, or approvals.' },
];

export const TYPE_COLORS: Record<string, string> = {
    Admin: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300',
    Executive: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300',
    Finance: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300',
    HR: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300',
    IT: 'bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300',
    Legal: 'bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-300',
    Procurement: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300',
    Operations: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300',
    Quality: 'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-300',
    Fleet: 'bg-brand-sky-100 text-brand-sky-700 dark:bg-brand-sky-900/30 dark:text-brand-sky-300',
    Warehouse: 'bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-300',
    Contracts: 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300',
    Audit: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300',
};

export const NAVIGATION_SECTIONS = [
    { title: 'Dashboard', icon: LayoutDashboard, color: 'bg-brand-sky-500', desc: 'Your home page after logging in. Shows all system modules as cards in a grid. Click any card to go directly to that module.', where: 'Home page' },
    { title: 'Sidebar Navigation', icon: Navigation, color: 'bg-indigo-500', desc: 'Each module has its own sidebar menu. When you enter a module, the sidebar shows only the pages and actions for that module. Use "Back to Dashboard" to return.', where: 'All pages' },
    { title: 'Breadcrumb Trail', icon: Search, color: 'bg-violet-500', desc: 'The breadcrumb at the top of every page shows where you are. Click any part of it to jump back to a previous page.', where: 'All pages' },
    { title: 'Search & Filters', icon: Search, color: 'bg-emerald-500', desc: 'Use the search bar and filter dropdowns on listing pages to quickly find what you need by name, number, status, or other criteria.', where: 'List pages' },
    { title: 'Data Tables', icon: ClipboardList, color: 'bg-amber-500', desc: 'Records are shown in tables with sorting, pagination, and action buttons (View, Edit, Delete). You can choose how many rows to show per page.', where: 'List pages' },
    { title: 'Export & Refresh', icon: RefreshCw, color: 'bg-cyan-500', desc: 'Export your data to Excel, or click the refresh button to reload the latest data without leaving the page.', where: 'List pages' },
];

export const WORKFLOW_STEPS = [
    {
        title: 'Client Approval Workflow', icon: Users, color: 'bg-purple-500',
        desc: 'When a new client is added to the system, it must go through an approval process to verify the client information and authorize business dealings.',
        steps: [
            { actor: 'Any Staff', action: 'Creates a new client record with company name, contact details, and supporting documents. The record enters Draft status.', status: 'Draft' },
            { actor: 'Department Head', action: 'Reviews the client information for completeness and accuracy. If satisfactory, submits for formal approval. If issues found, returns to creator for corrections.', status: 'Pending' },
            { actor: 'Authorized Approver', action: 'Evaluates the client against business criteria. Can approve to activate the client, or reject with a detailed explanation for the rejection reason.', status: 'Approved / Rejected' },
            { actor: 'System', action: 'Upon approval, the client status changes to Active. The client is now available for creating contracts, invoices, and linking to projects.', status: 'Active' },
        ],
    },
    {
        title: 'Financial Disbursement Workflow', icon: DollarSign, color: 'bg-emerald-500',
        desc: 'Payment disbursements follow a strict approval chain to ensure proper financial controls and authorization at each level.',
        steps: [
            { actor: 'Finance Staff', action: 'Creates a disbursement request specifying the recipient, amount, purpose, bank account, and attaches supporting invoices or purchase orders.', status: 'Draft' },
            { actor: 'Finance Manager', action: 'Reviews the disbursement for budget availability, verifies supporting documents, ensures compliance with financial policies, and forwards for executive approval.', status: 'Under Review' },
            { actor: 'CFO', action: 'Provides financial authorization, verifying the transaction aligns with budget plans and organizational financial strategy.', status: 'Approved' },
            { actor: 'CEO', action: 'For high-value transactions exceeding the CFO\'s authority limit, the CEO provides the final executive sign-off.', status: 'Executed' },
        ],
    },
    {
        title: 'Project Contract Workflow', icon: FileCheck, color: 'bg-teal-500',
        desc: 'Contracts with subcontractors undergo commercial, legal, and executive review before they can be executed and work can begin.',
        steps: [
            { actor: 'Contracts Staff', action: 'Drafts the contract document with scope of work, terms and conditions, payment milestones, and deliverable specifications.', status: 'Draft' },
            { actor: 'Commercial Director', action: 'Reviews the commercial terms including pricing, payment schedule, penalties, and ensures the contract is commercially viable.', status: 'Under Review' },
            { actor: 'Legal Director', action: 'Conducts a legal review to ensure contractual terms comply with applicable laws, identifies legal risks, and suggests protective clauses.', status: 'Legal Review' },
            { actor: 'CEO / CFO', action: 'Provides final authorization based on the commercial and legal reviews. Upon approval, the contract becomes active and work can commence.', status: 'Executed' },
        ],
    },
    {
        title: 'Task Order Workflow', icon: ClipboardList, color: 'bg-amber-500',
        desc: 'Task orders are the operational units of project execution. Each task order goes through assignment, execution, and quality verification stages.',
        steps: [
            { actor: 'Operations Staff', action: 'Creates a task order specifying the work to be done, linked to a project and contract, with a detailed scope, timeline, and resource requirements.', status: 'Created' },
            { actor: 'Operations Manager', action: 'Reviews the task scope, allocates resources and equipment, assigns the field team, and approves the execution plan.', status: 'Assigned' },
            { actor: 'Field Team', action: 'Executes the task in the field, documents progress with photos and reports, and notifies management upon completion.', status: 'In Progress' },
            { actor: 'Quality Director', action: 'Conducts a quality inspection of the completed work, verifies it meets specifications, and provides the final sign-off.', status: 'Completed' },
        ],
    },
];

export const FAQ_ITEMS = [
    { q: 'How do I reset my password?', a: 'Go to Settings > Profile from the sidebar. Click "Change Password" and enter your current password followed by your new password. Passwords must be at least 8 characters with uppercase, lowercase, and special characters. If you forget your password entirely, contact your IT administrator who can reset it for you.' },
    { q: 'Why can\'t I access a certain module?', a: 'Access is controlled by your role and permissions. Each role has specific permissions (View, Create, Edit, Delete, Approve) for each module. If you need access to a module that you currently can\'t see, contact your IT administrator — they can either change your role or give you individual access to the specific features you need.' },
    { q: 'How do approval workflows work?', a: 'When you create a record that requires approval (client, contract, payment, etc.), it enters a "Pending" state. The record then moves through reviewers who either approve or reject it. Each step is logged with timestamps and comments. You can track the progress from the record\'s detail page. If rejected, you\'ll see the reviewer\'s comment — make corrections and resubmit.' },
    { q: 'Can I export data from the system?', a: 'Yes! Most listing pages have an "Export Excel" button that downloads the current data as a spreadsheet. You can also generate PDF reports from the Reports module. Tip: apply your filters first, then export — only the filtered data will be downloaded.' },
    { q: 'What happens when a record is deleted?', a: 'Most records are not permanently removed — they are deactivated instead, so the system keeps a history for audit purposes. Only System Administrators and authorized Directors can typically delete records. If you accidentally delete something, contact your administrator.' },
    { q: 'How does the AI Assistant work?', a: 'The AI Assistant helps you analyze your data by simply asking questions in plain language. For example, you can ask "What was our total spending last month?" or "Show me overdue projects." It also includes specialized tools for financial analysis, budget forecasting, anomaly detection, and smart summaries. Navigate to the AI module from the dashboard to get started.' },
    { q: 'What is the difference between Roles and Individual Permissions?', a: 'Your Role (like Finance Staff or HR Director) gives you a default set of permissions — things you can see and do. But sometimes you need extra access, or a specific permission removed. The IT team can adjust your individual permissions without changing your role. For example, you might be HR Staff but get extra permission to delete records.' },
    { q: 'How do I navigate between modules?', a: 'Use the Dashboard as your home page — it shows all system modules as cards in a grid. Click any card to enter that module. Inside a module, the sidebar on the left shows you the available pages and actions. Click "Back to Dashboard" in the sidebar to return to the main page.' },
    { q: 'What browsers are supported?', a: 'BEAM works best on modern browsers: Chrome 90+, Firefox 88+, Safari 14+, and Edge 90+. Make sure JavaScript and cookies are enabled. The system works on desktop, tablet, and mobile devices — the layout adjusts automatically to your screen size.' },
    { q: 'How are notifications handled?', a: 'You\'ll receive in-app notifications for pending approvals, status changes, and important updates. You can customize what notifications you receive in Settings > Notifications. Email notifications are also sent for critical events like pending approvals and rejected requests.' },
    { q: 'What does the System Administrator role do?', a: 'The System Administrator has full, unrestricted access to everything in the system — every module, every record, and every action. This role is meant for system maintenance and should only be given to 1-2 trusted people. If you need something done that requires admin access, contact your System Administrator.' },
    { q: 'How do I add a new employee to the system?', a: 'It\'s a two-step process: First, create the employee record in the Employees module (enter their name, job title, department, salary, etc.). Then, create a User account in the Users module and assign them a role. Link the user account to the employee record. They can now log in and start using the system!' },
    { q: 'Can I customize the dashboard?', a: 'The dashboard shows all system modules as cards in a grid. The modules you see depend on your role — if you don\'t have access to a module, its card won\'t appear. The layout automatically adjusts to your screen size (more columns on larger screens, fewer on mobile).' },
    { q: 'How quickly do permission changes take effect?', a: 'When the IT team updates your permissions, the changes typically take effect within a few minutes. If you notice that a change hasn\'t applied yet, try logging out and back in, or wait a couple of minutes and refresh the page.' },
    { q: 'What is the email format for user accounts?', a: 'All user emails follow the format username@beam.local — for example, hr_dir@beam.local, cfo@beam.local, or admin@beam.local. You\'ll use this email to log in to the system.' },
];
